DIR_MK_TMPL := ../mk_tmpl
DIR_DEBUG_BIN := ../bin
DIR_RELEASE_BIN := ../bin
CC_INCLUDE_EXT := ../include
CC_LK_OBJS_DEBUG := $(DIR_DEBUG_BIN)/libjnu_d.a
CC_LK_OBJS_RELEASE := $(DIR_RELEASE_BIN)/libjnu.a
BIN_RELEASE_NAME := jnu_test
BIN_DEBUG_NAME := jnu_test_d

-include $(DIR_MK_TMPL)/app.mk
